apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: mahmoud@muljin.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector:
        dnsZones:
        - nowleave.com
      dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIAQ45YAOBUDHURCMUM
          secretAccessKeySecretRef:
            name: nowleave.certmanager.route53
            key: secret-access-key
